apiVersion: batch/v1
kind: CronJob
metadata:
  name: grocy-db-backup
  labels:
    {{- include "elzokalo-grocy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Backup the database every day at 02:00
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: grocy-backup-job
        spec:
          restartPolicy: Never
          containers:
            - name: "backup"
              image: amazon/aws-cli:2.19.5
              imagePullPolicy: Always
              command: ["s3", "sync", "/var/www/data", "s3://elzokalo-grocy-backup/{{ now }}"]
              volumeMounts:
                - name: db
                  mountPath: /var/www/data
                  subPath: job
              envFrom:
                - secretRef:
                    name: "{{ template "elzokalo-grocy.fullname" . }}-secrets"
          volumes:
            - name: db
              persistentVolumeClaim:
                claimName: grocy