kind: Secret
apiVersion: v1
metadata:
  name: {{ template "elzokalo-grocy.fullname" . }}-secrets
  labels:
{{ include "elzokalo-grocy.labels" . | indent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ "" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ "" | b64enc }} 
  AWS_DEFAULT_REGION: {{ "eu-west-3" | b64enc }} 