apiVersion: v1
kind: Service
metadata:
  name: grocy
  labels:
    {{- include "elzokalo-grocy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: grocy